apiVersion: v1
kind: Service
metadata:
  name: apache
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: apache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: httpd
          ports:
            - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache-ingress
  namespace: default
  annotations:
    cert-manager.io/issuer: prod-issuer
    cert-manager.io/issuer-kind: OriginIssuer
    cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
spec:
  ingressClassName: nginx
  rules:
    - host: apache.rurich.dev
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: apache
                port:
                  number: 80
  tls:
    - hosts:
        - apache.rurich.dev
      secretName: apache-tls
